[package]
name = "link-checker-rs"
version = "0.1.0"
authors = ["Imran Khan <imrankhan@teknik.io>"]
edition = "2018"

[dependencies]
reqwest = { version = "*", features = ["rustls-tls"] }
tokio = { version = "*", features = ["full"] }
anyhow = "*"
futures = "*"
